[package]
name = "escher_video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "*"
cmake = "*"
pkg-config = "*"

[dependencies]
bitflags = "*"
wgpu = "*"


